# Generated by Django 5.2.7 on 2025-11-04 20:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Route')),
                ('start_date', models.DateTimeField(verbose_name='Start time')),
                ('max_people', models.IntegerField(verbose_name='Max number of passengers')),
                ('description', models.TextField(verbose_name='Description')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.car', verbose_name='Route car')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Route owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Route')),
                ('start_date', models.DateTimeField(verbose_name='Start time')),
                ('max_weight', models.IntegerField(verbose_name='Max weight (kg)')),
                ('max_width', models.IntegerField(verbose_name='Max width (cm)')),
                ('max_height', models.IntegerField(verbose_name='Max height (cm)')),
                ('max_depth', models.IntegerField(verbose_name='Max depth (cm)')),
                ('description', models.TextField(verbose_name='Description')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='accounts.car', verbose_name='Route car')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Route owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
