# Generated by Django 5.2.7 on 2025-11-08 21:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Start')),
                ('end', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Start')),
                ('weight', models.IntegerField(verbose_name='weight (kg)')),
                ('width', models.IntegerField(verbose_name='width (cm)')),
                ('height', models.IntegerField(verbose_name='height (cm)')),
                ('depth', models.IntegerField(verbose_name='depth (cm)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_transport_route', to='route.transportroute', verbose_name='Joined route')),
            ],
        ),
    ]
