# Generated by Django 5.2.7 on 2025-11-09 22:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_jointransportroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPassengerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Start')),
                ('end', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Start')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_passenger_route', to='route.transportroute', verbose_name='Joined route')),
            ],
        ),
    ]
