# Generated by Django 5.2.7 on 2025-11-09 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_joinpassengerroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpassengerroute',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jointransportroute',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
    ]
