# Generated by Django 5.2.7 on 2025-11-10 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_joinpassengerroute_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinpassengerroute',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_passenger_route', to='route.passengerroute', verbose_name='Joined route'),
        ),
    ]
