# Generated by Django 5.2.7 on 2025-11-10 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_joinpassengerroute_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpassengerroute',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Route owner'),
        ),
        migrations.AddField(
            model_name='jointransportroute',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Route owner'),
        ),
    ]
